export const mySelf = {
  name: "Linn Myat Maung",
  nickname: "Lucas",
  dob: "22th January 2003",
  gender: "Male",
  birthPlace: "Ann Township, Rakhine State, Myanmar",
  quote:
    "I wasn’t born to live easy. I was born to write, build, fail, rise, and fly.",
  personality: "Ambivert | INFJ",
  values: ["Honesty", "Curiosity", "Growth mindset"],
  height: "5'10\"",
  contacts: {
    phone: "+95 9696265132",
    email: "linnmyatmaung03@gmail.com",
    linkedin: "www.linkedin.com/in/linn-myat-maung-48b4a8355",
    github: "https://github.com/linnmyatmaung",
    resume:
      "https://drive.google.com/file/d/1dWO4RI7WwAkiexZfEskZagaPvI91cddP/view?usp=drive_link",
    facebook: "Linn Myat Maung",
  },
  relationshipStatus: "Single",
  favourites: {
    color: ["White", "Black"],
    sport: ["Football"],
    music: ["Hip Hop", "Trap", "Drill", "Jersey"],
    artists: "Juice Wrld",
    songs: ["All girls are the same", "The Nights"],
    movie: ["Peaky Blinders", "Money Heist", "Harry Potter"],
    anime: ["One Piece!!", "Jujutsu Kaisen", "Your Name"],
    character: ["Thomas Shelby", "Sanji"],
    food: ["ချိုချဉ်ကြော်", "မုန့်ဟင်းခါး", "လက်ဖက်သုပ်"],
    coffee: ["Mocha", "Latte"],
    tea: ["ပုံမှန်", "ကျစိမ့်", "ချိုစိမ့်"],
    girl_type: ["Smart", "Funny", "Kind", "Loyal", "Honest"],
  },
  occupation: "Software Engineer | Full Stack Developer | Java Developer",
  hobbies: ["Coding", "Reading", "Listening to music", "Gym"],
  location: "Yangon, Myanmar",
  languages: ["English", "Burmese"],
  schools: {
    highSchool: {
      name: "B.E.H.S (2) Ann",
      matriculationMarks: 463,
      distinctionSubjects: ["English", "Chemistry", "Biology"],
    },
    universities: {
      2019_2025: {
        name: "University Of Technology( Yatanarpon Cyber City) (UTYCC)",
        specialization: "Information Science Technology(IST)",
      },
      2020_2025: {
        name: "University Of People(UoPeople",
        specialization: "Computer Science",
        course_works: [
          "Programming",
          "Networking",
          "Database Design and Development",
          "Professional Practice",
          "Web Development",
          "Seurity",
          "Project Management",
          "Business Intelligence",
          "Maths for Computing",
          "Cloud Computing",
          "Internet of Things",
          "Advanced Programming",
          "Computing Research Project",
          "Discrete Mathematics",
          "Data Structures and Alogorithms",
          "AI",
        ],
      },
    },
  },
  education: {
    degree: "Bachelor of Science in Computer Science",
    university: "University of People",
    course_works: [
      "Android Development",
      "Artificail Intelligence",
      "Advanced Cybersecurity",
      "Advanced Data Technologies",
      "Research",
      "Product Development",
    ],
    graduationYear: 2025,
  },
  skills: [
    "Java",
    "Spring Boot",
    "JavaScript",
    "TypeScript",
    "React",
    "NEXT.js",
    "Node.js",
    "Express.js",
    "RESTful API",
    "SQL",
    "MongoDB",
    "AWS",
  ],
  favouriteTechnologies: ["React", "Tanstack Query", "Redux Toolkit", "AWS"],
  funFacts: [
    "If I code till dawn, it's because I chase dreams — not deadlines.",
    "Coffee powers my grind. Beer celebrates my victories. Code builds my legacy.",
    "I wasn't born to live easy. I was born to write, build, fail, rise, and fly.",
    "My code may crash, my servers may fall — but my will never breaks.",
    "Some sip coffee to wake up. I sip to wake the beast who writes the future.",
    "I grind so that when I m gone, my code still speaks.",
    "Life is short. Code hard. Brew stronger. Laugh louder.",
    "Today’s bugs are tomorrow’s lessons. Today’s grind is tomorrow’s glory.",
    "I drink coffee to fuel the fire. I drink beer to celebrate the burn.",
    "Code like it is your last day. Debug like the world depends on you. Fly like you wrote the wind.",
  ],

  alterEgo: "Fearless, chaotic, and always chasing the next big dream",
};
